### ISSUE TITLE
Signature mismatch

### ISSUE THREAD

**Issue by lilymaybenichou** [dotnet/AspNetCore.Docs.fr-fr#243]
In the last code sample I think this 
public async Task&lt;ActionResult&lt;TodoItem&gt;&gt; CreateTodoItem(TodoItemDTO todoItemDTO)
should become 
public async Task&lt;ActionResult&lt;TodoItemDTO&gt;&gt; CreateTodoItem(TodoItemDTO todoItemDTO)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Didacticiel : créer une API Web avec ASP.NET Core](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @lilymaybenichou
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #17528](https://github.com/dotnet/AspNetCore.Docs/issues/17528) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @lilymaybenichou, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17528. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
