### ISSUE TITLE
Error because "Rating" empty

### ISSUE THREAD

**Issue by Koulbrise1030** [dotnet/AspNetCore.Docs.fr-fr#246]
I get an error adding the [Required] attribute in the "Rating" class.
You must fill in the "Rating" data to avoid having the error

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Ajouter une validation à une application ASP.NET Core MVC](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/dotnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Koulbrise1030
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #18163](https://github.com/dotnet/AspNetCore.Docs/issues/18163) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Koulbrise1030, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/18163. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
